### ISSUE TITLE
Missing return statement in InviteCommand

### ISSUE THREAD

**Issue by BaconOFBurger** [pretendlake/old-parties#7]
At: https://github.com/Diduhless/Parties/blob/master/src/Diduhless/Parties/command/presets/InviteCommand.php#L46
you forgot to add a return. If the player has no party and he try invite a player it will result into a kick due "internal server error"

**Comment by BaconOFBurger** [comment]
Also even if you add a return, it send the help message for commands (list of commands) instead of saying you have to create a party first 😃

**Comment by pretendlake** [comment]
Issue fixed, I forgot to close it in the commit message.
